name: Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: "Create env file"
        run: |
          touch .env
          echo SKIP_ENV_VALIDATION="true" >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
          echo ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} >> .env
          echo ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} >> .env
          echo BLOG_LANGUAGE=${{ secrets.BLOG_LANGUAGE }} >> .env
          echo BLOG_NAME=${{ secrets.BLOG_NAME }} >> .env
          echo BLOG_THEME=${{ secrets.BLOG_THEME }} >> .env
          echo BLOG_KEYWORDS=${{ secrets.BLOG_KEYWORDS }} >> .env
          echo LOCALIZE_MONTHS_BY_LANG=${{ secrets.LOCALIZE_MONTHS_BY_LANG }} >> .env
          cat .env
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma
        run: npm run postinstall
      - name: Push Prisma
        run: npm run db:push --accept-data-loss
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
